version: "3"

# Task Management Application - Main Taskfile
# This file orchestrates development, testing, building, and deployment tasks
# using composition of individual service Taskfiles

includes:
  api:
    taskfile: ./services/api/Taskfile.yml
    dir: ./services/api
    internal: true
  worker:
    taskfile: ./services/worker/Taskfile.yml
    dir: ./services/worker
    internal: true
  common:
    taskfile: ./packages/playground_common/Taskfile.yml
    dir: ./packages/playground_common
    internal: true
  app:
    internal: true
    taskfile: ./app/Taskfile.yml
    dir: ./app


tasks:

  default:
    desc: "Show available tasks (default command)"
    cmds:
      - task --list

  help:
    desc: "Show available tasks"
    cmds:
      - task --list


  setup:
    desc: "Set up the entire development environment (includes dev dependencies)"
    aliases: [install]
    deps: [common:deps:dev, api:deps:dev, worker:deps:dev, app:deps]


  dev:
    desc: "Start all services for local development"
    aliases: [dev:local, run]
    deps: [setup, api:dev, worker:dev, app:dev]


  test:
    desc: "Run all tests (unit + e2e)"
    aliases: [tests]
    deps: [common:test, api:test, worker:test, app:test]


  lint:
    desc: "Run all linters and formatters"
    deps: [common:lint, api:lint, worker:lint, app:lint]


  format:
    desc: "Format all code"
    deps: [common:format, api:format, worker:format, app:format]


  build:
    desc: "Build all services and frontend (production dependencies only)"
    deps: [common:build, api:build, worker:build, app:build]

  clean:
    desc: "Clean build artifacts and caches"
    deps: [common:clean, api:clean, worker:clean, app:clean]
    cmds:
      - rm -rf dist/ build/ coverage/


  doctor:
    desc: "Check for required development dependencies"
    silent: true
    cmds:
      - |
        if ping -c 1 8.8.8.8 >/dev/null 2>&1; then
          echo "✅ Network connectivity is working"
        else
          echo "❌ No network connectivity detected"
        fi
      - |
        if scutil --nc status "Cato Networks VPN" | grep -q "^Connected"; then
          echo "✅ Cato VPN is active"
        else
          echo "⚠️  Cato VPN is not active"
        fi
      - |
        AWS_ERROR=$(aws sts get-caller-identity 2>&1)
        if [ $? -eq 0 ]; then
          AWS_ACCOUNT=$(echo "$AWS_ERROR" | jq -r '.Account' 2>/dev/null)
          AWS_ARN=$(echo "$AWS_ERROR" | jq -r '.Arn' 2>/dev/null)
          echo "✅ AWS credentials are valid (Account: $AWS_ACCOUNT)"
          
          # Check if the assumed role contains Hive-Eng-Dev (works for both SSO and direct role assumption)
          if echo "$AWS_ARN" | grep -q "Hive-Eng-Dev"; then
            echo "✅ Using Hive-Eng-Dev role via AWS SSO"
          else
            echo "❌ Not using Hive-Eng-Dev role"
            echo "   Current role: $AWS_ARN"
            echo "   Expected role to contain: Hive-Eng-Dev"
          fi
        else
          if echo "$AWS_ERROR" | grep -q "ExpiredTokenException\|expired"; then
            echo "❌ AWS credentials are expired"
            echo "   Run: aws sso login"
          elif echo "$AWS_ERROR" | grep -q "UnauthorizedOperation\|AccessDenied"; then
            echo "❌ AWS credentials are unauthorized"
            echo "   Check your AWS permissions"
          else
            echo "❌ AWS credentials are invalid or not configured"
            echo "   Run: aws configure or aws sso login"
          fi
        fi
      - task: app:doctor
      - task: common:doctor
      - |
        if command -v git >/dev/null 2>&1; then
          GIT_VERSION=$(git --version)
          echo "✅ git is installed ($GIT_VERSION)"
        else
          echo "❌ git is not installed or not in PATH"
          echo "   Install git: https://git-scm.com/downloads"
        fi
      - |
        if command -v aws >/dev/null 2>&1; then
          AWS_VERSION=$(aws --version)
          echo "✅ awscli is installed ($AWS_VERSION)"
        else
          echo "❌ awscli is not installed or not in PATH"
          echo "   Install awscli: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html"
        fi
      - |
        if [ "$SHELL" = "/bin/zsh" ] || [ "$0" = "zsh" ] || [ "$(basename $SHELL)" = "zsh" ]; then
          ZSH_VERSION=$(zsh --version 2>/dev/null | head -n1 || echo "version check failed")
          echo "✅ zsh is the current shell ($ZSH_VERSION)"
        else
          echo "⚠️  zsh is not the current shell (current: $SHELL)"
          echo "   Consider switching to zsh for better development experience"
        fi
