enableGlobalCache: true

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-stable-temp.cjs

npmRegistries:
  'https://pagaya-artifacts-704102000649.d.codeartifact.us-east-1.amazonaws.com/npm/hive/':
    npmAlwaysAuth: true
    npmAuthToken: '${CODEARTIFACT_AUTH_TOKEN}'

npmRegistryServer: 'https://pagaya-artifacts-704102000649.d.codeartifact.us-east-1.amazonaws.com/npm/hive/'
