version: "3"

# Common Package Taskfile
# Handles shared library tasks

vars:
  SERVICE_NAME: common
  PYTHON_SRC: common
  TESTS_DIR: tests

tasks:
  default:
    desc: "Show available tasks (default command)"
    cmds:
      - task --list

  deps:
    desc: "Install dependencies for common package (production only)"
    cmds:
      - uv sync

  deps:dev:
    desc: "Install development dependencies for common package"
    cmds:
      - uv sync --extra dev

  sync:
    desc: "Sync exact dependencies from lock files"
    cmds:
      - uv sync --frozen

  sync:dev:
    desc: "Sync exact development dependencies from lock files"
    cmds:
      - uv sync --frozen --extra dev

  test:
    desc: "Run tests for common package"
    cmds:
      - uv sync --extra dev
      - uv run pytest {{.TESTS_DIR}}/ -v
    status:
      - test -d {{.TESTS_DIR}}

  test:unit:
    desc: "Run unit tests for common package"
    cmds:
      - task: test

  lint:
    desc: "Run linting and formatting for common package"
    cmds:
      - uv sync --extra dev
      - uv run ruff check {{.PYTHON_SRC}} --fix
      - uv run ruff format {{.PYTHON_SRC}}

  format:
    desc: "Format code only"
    cmds:
      - uv sync --extra dev
      - uv run ruff format {{.PYTHON_SRC}}

  build:
    desc: "Build common package (production dependencies only)"
    cmds:
      - uv build

  clean:
    desc: "Clean build artifacts for common"
    cmds:
      - rm -rf dist/ build/ .pytest_cache/
      - find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true

  dev:install:
    desc: "Install common package in development mode"
    cmds:
      - uv sync

  doctor:
    desc: "Check Python development dependencies (uv)"
    silent: true
    cmds:
      - |
        if command -v uv >/dev/null 2>&1; then
          UV_VERSION=$(uv --version)
          echo "✅ uv is installed ($UV_VERSION)"
        else
          echo "❌ uv is not installed or not in PATH"
          echo "   Install uv: https://docs.astral.sh/uv/getting-started/installation/"
        fi

