[project]
name = "common"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Yotam Manor", email = "yotammanor@gmail.com" }
]
requires-python = ">=3.10,<3.11"
dependencies = [
    "pydantic>=2.11.0,<2.12.0",
    "sqlalchemy>=1.3.0,<1.4.0",
    "email-validator>=2.0.0",
    "psycopg2>=2.9.0,<3.0.0",
]

[project.optional-dependencies]
dev = [
    "ruff>=0.5.0",
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "pytest-mock>=3.10.0",
]

[[tool.uv.index]]
name = "CODEARTIFACT"
url = "https://pagaya-artifacts-704102000649.d.codeartifact.us-east-1.amazonaws.com/pypi/Pagaya-Artifacts-prod/simple/"

[tool.uv]
keyring-provider = "subprocess"

[tool.ruff]
# Extend the root configuration
extend = "../../.ruff.toml"



[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
